platform :ios, '9.0'

target 'FishBowl' do
  use_frameworks!
	
  pod 'Material', :git  => 'https://github.com/CosmicMind/Material.git', :branch => 'swift-2.3'
  pod 'OAuthSwift', :git => 'https://github.com/OAuthSwift/OAuthSwift.git', :branch => 'swift2.3'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'ReachabilitySwift', '~> 2.4'
end